@extends('front.layout.app')

@section('maincontent')
<!-- Start Page Banner -->
<div class="page-banner-area item-bg1">
            <div class="m-auto">
                <div class="">
                    <div class="container">
                        <div class="page-banner-content">
                            <h2>Best digital marketing company</h2>
                            <ul>
                                <li>
                                    <a href="index.html">Home</a>
                                </li>
                                <li>Best digital marketing company</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Page Banner -->


        <!-- about-360 IT HUB-area-start -->
        <div class="rs-achievement style1 relative md-pt-80 mt-5">
         <div class="container">
            <div class="row">
               <div class="col-lg-6">
                  <div class="sec-title4 mb-25">
                     <div class="sec-title3">
                        <span class="sub-text">Best digital marketing company </span>
                     </div>
                     <h1 class="title">Best digital marketing   <span class="red">company</span></h1>
                     <div class="desc left-line-v">
                        <div class="draw-line start-draw"></div>
                        Being online and connected has changed the way we buy goods, find out about events, and may even impact how we vote. One of the causes digital marketing has altered how organizations advertise and sell goods and services is the ability to use the internet at nearly any time. </div>
                  </div>
                  <p>We are the Best digital marketing company in India offering four major benefits over traditional marketing methods: measurability, cost, speed, and engagement.</p>

                 <div class="crypto_mlm_btns mt-4 mb-3">
                     <a href="tel:+91 9513777001" class="btn consult_btn cryptmlmwhatsappbtn_color" name="button"><i class="fa fa-whatsapp"></i> | WhatsApp </a>
                     <a href="tel:+91 9513777001" class="btn consult_btn cryptmlmtelegrambtn_color ml-1" name="button"><i class="fa fa-telegram"></i> | Telegram</a>
                  </div>
               </div>
               <div class="col-lg-6 img-maT">
                  <figure class="rounded">
                     <img src="website-assets-22/images/about/abou_img.jpg" alt="" class="img-fluid rounded">
                  </figure>
               </div>
            </div>
            <div class="row my-3">
               <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div>
                        <div class="icon btn btn-circle-sm disabled btn-soft-primary me-4 fontW-700"><span class="number fs-18">1</span> </div>
                     </div>
                     <div>
                        <h4>Measurability</h4>
                        <p class="mb-2">A website is undoubtedly the single most significant marketing tool, providing information about what people engage in as well as how they find and navigate your website. How many visitors have been to your website? Are they generated by organic search, pay-per-click (PPC), social media, or email campaigns? You may track the evolution of your numbers over time to see whether our marketing strategy is reaching the proper individuals. We are therefore considered the Best digital marketing company in Bengaluru.</p>
                     </div>
                  </div>
               </div>
               <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div>
                        <div class="icon btn btn-circle-sm disabled btn-soft-primary me-4 fontW-700"><span class="number fs-18">2</span> </div>
                     </div>
                     <div>
                        <h4>Affordability</h4>
                         <p class="mb-2">Because of its cost, digital marketing has brought marketing to medium and small businesses all around the world, placing them on a level playing field with larger corporations. At the same time, you have far more reach with a larger audience that might cover the entire globe.</p>
                     </div>
                  </div>
               </div>
               <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div>
                        <div class="icon btn btn-circle-sm disabled btn-soft-primary me-4 fontW-700"><span class="number fs-18">3</span> </div>
                     </div>
                     <div>
                        <h4>Values</h4>
                         <ul class="list-unstyled">
                            <li style="list-style: square;">
                              <h5>Speed</h5>
                               <p class="mb-2">You may also get your word out there faster in the virtual environment - all it takes is a simple click of a button. When opposed to the considerably lengthy process of producing and distributing printed advertising, this implies that businesses may be much more nimble with their digital marketing strategy offered by the Best digital marketing company in Bengaluru.
                               </p>
                            </li>
                         </ul>
                     </div>
                  </div>
               </div>


               <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div class="list-title top-spaceg">
                         <ul class="list-unstyled">
                            <li>
                              <h5>Engagement</h5>
                               <p class="mb-2">Our Digital marketing service provides you a dynamic benefit in how you sell yourself in today's fast-paced environment.
                               </p>
                               <p class="mb-2">One of the primary grounds digital marketing has grown in importance is the ability to speak with prospective and present clients, answer inquiries, and handle concerns. You may also engage with a larger audience, which means you can do more than sell.
                                    You may get views and do market research to help you make better decisions. You might also look for collaborations or campaigns. You may raise your visibility and gain their endorsement by encouraging your viewers to share pages with the help of the Best digital marketing company in India.
                                    </p>
                               <p class="mb-2">Other routes for engagement include competitions, blogs, public relations, events, and other marketing efforts.</p>
                            </li>
                         </ul>
                     </div>
                  </div>
               </div>
              <!-- <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div class="list-title">
                         <ul class="list-unstyled">
                            <li>
                              <h5>Agility</h5>
                               <p class="mb-2">To have the ability to react quickly to change and to respond accordingly.
                               </p>
                            </li>
                         </ul>
                     </div>
                  </div>
               </div>
               <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div class="list-title">
                         <ul class="list-unstyled">
                            <li>
                              <h5>Efficiency</h5>
                               <p class="mb-2">To produce more output in a shorter period of time, without sacrificing quality.
                               </p>
                            </li>
                         </ul>
                     </div>
                  </div>
               </div>
                <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div class="list-title">
                         <ul class="list-unstyled">
                            <li>
                              <h5>Integrity</h5>
                               <p class="mb-2">To be consistent in words and action to the employees, external stakeholders and society.
                               </p>
                            </li>
                         </ul>
                     </div>
                  </div>
               </div>




            <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div>
                        <div class="icon btn btn-circle-sm disabled btn-soft-primary me-4 fontW-700"><span class="number fs-18">4</span> </div>
                     </div>
                     <div>
                        <h4>Exceeding customer expectations through innovation</h4>
                         <p class="mb-2">To always go beyond what we have now and constantly improve on current approaches of developing technical solutions and in the processes which
						support the development.</p>
                     </div>
                  </div>
               </div>
               <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div>
                        <div class="icon btn btn-circle-sm disabled btn-soft-primary me-4 fontW-700"><span class="number fs-18">5</span> </div>
                     </div>
                     <div>
                        <h4>Agility</h4>
                         <p class="mb-2">To have the ability to react quickly to change and to respond accordingly.</p>
                     </div>
                  </div>
               </div>
               <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div>
                        <div class="icon btn btn-circle-sm disabled btn-soft-primary me-4 fontW-700"><span class="number fs-18">6</span> </div>
                     </div>
                     <div>
                        <h4>Efficiency</h4>
                         <p class="mb-2">To produce more output in a shorter period of time, without sacrificing quality.</p>
                     </div>
                  </div>
               </div>
               <div class="col-lg-6">
                  <div class="d-flex flex-row">
                     <div>
                        <div class="icon btn btn-circle-sm disabled btn-soft-primary me-4 fontW-700"><span class="number fs-18">7</span> </div>
                     </div>
                     <div>
                        <h4>Integrity</h4>
                         <p class="mb-2">To be consistent in words and action to the employees, external stakeholders and society.</p>
                     </div>
                  </div>
               </div> -->
            </div>
         </div>
        </div>
        <!-- about-360 IT HUB-area-start -->


        <!-- =======our-service-provide-start===== -->
        <section class="content-inner-2 bg-color">
           <div class="container">
              <div class="text-center">
                  <div class="section-head-sectionService style-3 wow fadeInUp" data-wow-duration="2s" data-wow-delay="0.2s">
                   <h2 class="sub-title m-b15" style="color: #fff;">OUR SERVICES</h2>
                   <h3 class="title m-t10">We Provide <span class="red">Digital Services</span></h3>
                  </div>
              </div>
              <div class="row icon-wraper-1">
                  <div class="col-lg-4 col-md-6">
                    <div class="icon-bx-wraper style-3 style-h m-b30 box-hover wow fadeInUp">
                       <div class="icon-bx-sm radius bgl-primary">
                          <a class="icon-cell" href="index.html#">
                             <div class="icon-img">
                                <img src="website-assets-22/images/service-icon/icon-1.png" alt="Services" />
                                <img src="website-assets-22/images/service-icon/icon-1.png" alt="Services" />
                             </div>
                          </a>
                       </div>
                       <div class="wraper-effect"></div>
                       <div class="icon-content">
                          <h4 class="dlab-title m-b15">Web Development</h4>
                          <p>Web development service provider in India. We offer end to end solutions of web development, third party integration, and maintenance.</p>
                       </div>
                    </div>
                 </div>
                 <div class="col-lg-4 col-md-6">
                    <div class="icon-bx-wraper style-3 style-h m-b30 box-hover wow fadeInUp">
                       <div class="icon-bx-sm radius bgl-primary">
                          <a class="icon-cell" href="index.html#">
                             <div class="icon-img">
                                <img src="website-assets-22/images/service-icon/icon-3.png" alt="Services" />
                                <img src="website-assets-22/images/service-icon/icon-3.png" alt="Services" />
                             </div>
                          </a>
                       </div>
                       <div class="wraper-effect"></div>
                       <div class="icon-content">
                          <h4 class="dlab-title m-b15">DeFi Development</h4>
                          <p>A peerless level of performance to your business with a higher level of efficacy, security, and transparency.</p>
                       </div>
                    </div>
                 </div>
                 <div class="col-lg-4 col-md-6">
                    <div class="icon-bx-wraper style-3 m-b30 style-h box-hover wow fadeInUp">
                       <div class="icon-bx-sm radius bgl-primary">
                          <a class="icon-cell" href="index.html#">
                             <div class="icon-img">
                                <img src="website-assets-22/images/service-icon/icon-2.png" alt="Services" />
                                <img src="website-assets-22/images/service-icon/icon-2.png" alt="Services" />
                             </div>
                          </a>
                       </div>
                       <div class="wraper-effect"></div>
                       <div class="icon-content">
                          <h4 class="dlab-title m-b15">Crypto Exchange Development</h4>
                          <p>Our crypto exchange development company is offer fully customized software for Cryptocurrency.
                          </p>
                       </div>
                    </div>
                 </div>
                 <div class="col-lg-4 col-md-6">
                    <div class="icon-bx-wraper style-3 m-b30 style-h box-hover wow fadeInUp">
                       <div class="icon-bx-sm radius bgl-primary">
                          <a class="icon-cell" href="index.html#">
                             <div class="icon-img">
                                <img src="website-assets-22/images/service-icon/icon-4.png" alt="Services" />
                                <img src="website-assets-22/images/service-icon/icon-4.png" alt="Services" />
                             </div>
                          </a>
                       </div>
                       <div class="wraper-effect"></div>
                       <div class="icon-content">
                          <h4 class="dlab-title m-b15">Mobile App Development</h4>
                          <p>360 IT HUB is the best mobile app development company in India. We integrate, design web, Ios and android mobile apps with custom management service.</p>
                       </div>
                    </div>
                 </div>
                 <div class="col-lg-4 col-md-6">
                    <div class="icon-bx-wraper style-3 m-b30 style-h box-hover wow fadeInUp">
                       <div class="icon-bx-sm radius bgl-primary">
                          <a class="icon-cell" href="index.html#">
                             <div class="icon-img">
                                <img src="website-assets-22/images/service-icon/icon-5.png" alt="Services" />
                                <img src="website-assets-22/images/service-icon/icon-5.png" alt="Services" />
                             </div>
                          </a>
                       </div>
                       <div class="wraper-effect"></div>
                       <div class="icon-content">
                          <h4 class="dlab-title m-b15">E-Commerce Development</h4>
                          <p>We offer end-to-end custom E-Commerce development services including latest technology and CMS. 360 IT HUB is the best custom E-Commerce solutions provider.</p>
                       </div>
                    </div>
                 </div>
                 <div class="col-lg-4 col-md-6">
                    <div class="icon-bx-wraper style-3 m-b30 style-h box-hover wow fadeInUp">
                       <div class="icon-bx-sm radius bgl-primary">
                          <a class="icon-cell" href="index.html#">
                             <div class="icon-img">
                                <img src="website-assets-22/images/service-icon/icon-6.png" alt="Services" />
                                <img src="website-assets-22/images/service-icon/icon-6.png" alt="Services" />
                             </div>
                          </a>
                       </div>
                       <div class="wraper-effect"></div>
                       <div class="icon-content">
                          <h2 class="dlab-title m-b15">MLM Software Development</h2>
                          <p>360 IT HUB is provide best MLM sofware engineered to make the operations easy and feasible, depleting the resources to their utmost functionality.</p>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
        </section>
        <!-- =======our-service-provide-end===== -->



        <!-- ======MY WORK PROCESS start======= -->
        <section class="work-porcess-area section ptb-70">
           <div class="container">
              <div class="section-header text-center">
                 <h1 class="title">My Work <span class="red"> Process</span></h1>
                 <p>We are a passionate digital design agency that specializes in beautiful and easy-to-use digital design & web development services.</p>
              </div>
              <div class="process-info">
                 <div class="row">
                    <div class="col-md-3">
                       <div class="single-process first text-center">
                          <i class="fa fa-search"></i>
                          <h4>Research & <br> Discovery</h4>
                       </div>
                    </div>
                    <div class="col-md-3">
                       <div class="single-process secend text-center">
                          <i class="fa fa-cog" aria-hidden="true"></i>
                          <h4>Design & <br> Prototyping</h4>
                       </div>
                    </div>
                    <div class="col-md-3">
                       <div class="single-process thard text-center">
                          <i class="fa fa-globe" aria-hidden="true"></i>
                          <h4>Development</h4>
                       </div>
                    </div>
                    <div class="col-md-3">
                       <div class="single-process last text-center">
                          <i class="fa fa-refresh" aria-hidden="true"></i>
                          <h4>Maintenance & Support</h4>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
        </section>
        <!-- ======MY WORK PROCESS end======= -->


         <!-- ========our-happy-clients-start========= -->
                <section class="bg">
                   <div class="container ptb-100">
                    <div class="main-heading client-headin">
                        <h1>Our Happy <span class="red">Clients</span></h1>
                        <div class="section-heading-line"></div>
                    </div>
                    <div class="slider">
                       <div class="slide-track">
                        <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/7.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/12.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/3.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/4.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/14.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/26.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/1.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/8.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/9.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/10.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/11.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/27.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/13.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/5.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/15.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/16.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/17.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/18.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/19.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/20.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/21.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/22.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/23.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/24.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/25.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/26.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/2.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/28.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/29.png"/>
                              </a>
                           </div>
                           <div class="slide">
                             <a href="#!">
                                 <img src="website-assets-22/images/our-clients/30.png"/>
                              </a>
                           </div>
                       </div>
                    </div>
                   </div>
                </section>
            <!-- ========our-happy-clients-end========= -->


            <!-- =========contact-us-area-start========= -->
              <section class="ptb-70">
                 <div class="container">
                    <div class="row">
                       <div class="mapouter">
                          <div class="map-area">
                             <div class="gapmap">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d486.1137690173753!2d77.6309191413908!3d12.913495999999991!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae148d4936affd%3A0x86b081e17a52a7af!2s434%2C%2016th%20A%20Cross%20Rd%2C%20Sector%206%2C%20HSR%20Layout%2C%20Bengaluru%2C%20Karnataka%20560102!5e0!3m2!1sen!2sin!4v1663405233279!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                             </div>
                          </div>
                          <div class="map-form">
                            @include('front.template.contactform')
                          </div>
                       </div>
                    </div>
                 </div>
              </section>
            <!-- =========contact-us-area-end========= -->
@endsection

@section('extra-script')
<script>

</script>
@endsection
